blank_issues_enabled: false
contact_links:
  - name: Get help from the community on telegram, get the insights of ytdl
    url: https://t.me/ytdlgui
    about: Join the ytdl telegram for community-powered support!